FROM node:18 AS build
WORKDIR /app

COPY ./client/package*.json ./

RUN npm ci

COPY ./client ./

RUN npm run build



FROM nginx

WORKDIR /

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist ./var/www/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
